
name: allTest

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Git clone"
        uses: actions/checkout@v2

      - name: "Setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew

      - name: "Gradle test"
        run: ./gradlew test

      - name: "Upload Test Reports Folder"
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: build/test-results/test # path to where the xml test results are stored

  report:
    name: "Display Test Reports"
    runs-on: ubuntu-latest
    needs: test # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: "Download Test Reports Folder"
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: "Kotlin Test Report"
        uses: asadmansr/android-test-report-action@v1.2.0